// Code generated by protoc-gen-go. DO NOT EDIT.
// source: coin_transaction.proto

/*
Package cointransaction is a generated protocol buffer package.

It is generated from these files:
	coin_transaction.proto

It has these top-level messages:
	QueryRequest
	WriteRequest
	CoinSDKServiceResponse
*/
package cointransaction

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CoinSDKServiceResponse_Status int32

const (
	CoinSDKServiceResponse_success CoinSDKServiceResponse_Status = 0
	CoinSDKServiceResponse_other   CoinSDKServiceResponse_Status = 5
	CoinSDKServiceResponse_error   CoinSDKServiceResponse_Status = 9
)

var CoinSDKServiceResponse_Status_name = map[int32]string{
	0: "success",
	5: "other",
	9: "error",
}
var CoinSDKServiceResponse_Status_value = map[string]int32{
	"success": 0,
	"other":   5,
	"error":   9,
}

func (x CoinSDKServiceResponse_Status) String() string {
	return proto.EnumName(CoinSDKServiceResponse_Status_name, int32(x))
}
func (CoinSDKServiceResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 0}
}

// The query request
type QueryRequest struct {
	QueryString string `protobuf:"bytes,1,opt,name=query_string,json=queryString" json:"query_string,omitempty"`
}

func (m *QueryRequest) Reset()                    { *m = QueryRequest{} }
func (m *QueryRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()               {}
func (*QueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *QueryRequest) GetQueryString() string {
	if m != nil {
		return m.QueryString
	}
	return ""
}

// The write request
type WriteRequest struct {
	// use json to simplified the RPC service level
	JsonStr string `protobuf:"bytes,1,opt,name=jsonStr" json:"jsonStr,omitempty"`
}

func (m *WriteRequest) Reset()                    { *m = WriteRequest{} }
func (m *WriteRequest) String() string            { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()               {}
func (*WriteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *WriteRequest) GetJsonStr() string {
	if m != nil {
		return m.JsonStr
	}
	return ""
}

// The service response
type CoinSDKServiceResponse struct {
	Message string                        `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Status  CoinSDKServiceResponse_Status `protobuf:"varint,2,opt,name=status,enum=cointransaction.CoinSDKServiceResponse_Status" json:"status,omitempty"`
	// if QueryRequest the payload is a json str encoded by go json lib
	Payload string `protobuf:"bytes,3,opt,name=payload" json:"payload,omitempty"`
}

func (m *CoinSDKServiceResponse) Reset()                    { *m = CoinSDKServiceResponse{} }
func (m *CoinSDKServiceResponse) String() string            { return proto.CompactTextString(m) }
func (*CoinSDKServiceResponse) ProtoMessage()               {}
func (*CoinSDKServiceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CoinSDKServiceResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CoinSDKServiceResponse) GetStatus() CoinSDKServiceResponse_Status {
	if m != nil {
		return m.Status
	}
	return CoinSDKServiceResponse_success
}

func (m *CoinSDKServiceResponse) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryRequest)(nil), "cointransaction.QueryRequest")
	proto.RegisterType((*WriteRequest)(nil), "cointransaction.WriteRequest")
	proto.RegisterType((*CoinSDKServiceResponse)(nil), "cointransaction.CoinSDKServiceResponse")
	proto.RegisterEnum("cointransaction.CoinSDKServiceResponse_Status", CoinSDKServiceResponse_Status_name, CoinSDKServiceResponse_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CoinTransaction service

type CoinTransactionClient interface {
	// Create a coin transaction record in fabric network
	CreateTransaction(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*CoinSDKServiceResponse, error)
	// Query the transaction info from fabric
	QueryTransaction(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*CoinSDKServiceResponse, error)
	// Create a account for certain user
	CreateAccount(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*CoinSDKServiceResponse, error)
}

type coinTransactionClient struct {
	cc *grpc.ClientConn
}

func NewCoinTransactionClient(cc *grpc.ClientConn) CoinTransactionClient {
	return &coinTransactionClient{cc}
}

func (c *coinTransactionClient) CreateTransaction(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*CoinSDKServiceResponse, error) {
	out := new(CoinSDKServiceResponse)
	err := grpc.Invoke(ctx, "/cointransaction.CoinTransaction/CreateTransaction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coinTransactionClient) QueryTransaction(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*CoinSDKServiceResponse, error) {
	out := new(CoinSDKServiceResponse)
	err := grpc.Invoke(ctx, "/cointransaction.CoinTransaction/QueryTransaction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coinTransactionClient) CreateAccount(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*CoinSDKServiceResponse, error) {
	out := new(CoinSDKServiceResponse)
	err := grpc.Invoke(ctx, "/cointransaction.CoinTransaction/CreateAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CoinTransaction service

type CoinTransactionServer interface {
	// Create a coin transaction record in fabric network
	CreateTransaction(context.Context, *WriteRequest) (*CoinSDKServiceResponse, error)
	// Query the transaction info from fabric
	QueryTransaction(context.Context, *QueryRequest) (*CoinSDKServiceResponse, error)
	// Create a account for certain user
	CreateAccount(context.Context, *WriteRequest) (*CoinSDKServiceResponse, error)
}

func RegisterCoinTransactionServer(s *grpc.Server, srv CoinTransactionServer) {
	s.RegisterService(&_CoinTransaction_serviceDesc, srv)
}

func _CoinTransaction_CreateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoinTransactionServer).CreateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cointransaction.CoinTransaction/CreateTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoinTransactionServer).CreateTransaction(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoinTransaction_QueryTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoinTransactionServer).QueryTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cointransaction.CoinTransaction/QueryTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoinTransactionServer).QueryTransaction(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoinTransaction_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoinTransactionServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cointransaction.CoinTransaction/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoinTransactionServer).CreateAccount(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CoinTransaction_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cointransaction.CoinTransaction",
	HandlerType: (*CoinTransactionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTransaction",
			Handler:    _CoinTransaction_CreateTransaction_Handler,
		},
		{
			MethodName: "QueryTransaction",
			Handler:    _CoinTransaction_QueryTransaction_Handler,
		},
		{
			MethodName: "CreateAccount",
			Handler:    _CoinTransaction_CreateAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coin_transaction.proto",
}

func init() { proto.RegisterFile("coin_transaction.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0x51, 0x4b, 0x32, 0x41,
	0x14, 0x75, 0x15, 0x15, 0xaf, 0x7e, 0x9f, 0xfb, 0x0d, 0x1f, 0xb2, 0x04, 0x81, 0xed, 0x4b, 0x42,
	0xb0, 0xa0, 0xfd, 0x82, 0x34, 0xea, 0xa1, 0x17, 0xdd, 0x15, 0x22, 0x28, 0x64, 0x9a, 0x2e, 0xba,
	0x91, 0x33, 0xeb, 0xcc, 0xdd, 0xc0, 0xbf, 0xd3, 0x5b, 0x3f, 0xa3, 0x7f, 0x16, 0xb3, 0xae, 0xb4,
	0x68, 0x44, 0x41, 0x6f, 0x73, 0x0e, 0xf7, 0xdc, 0x73, 0xe6, 0xde, 0x0b, 0x1d, 0xa1, 0x62, 0x39,
	0x23, 0xcd, 0xa5, 0xe1, 0x82, 0x62, 0x25, 0x83, 0x44, 0x2b, 0x52, 0xac, 0x6d, 0xf9, 0x02, 0xed,
	0xf7, 0xa1, 0x35, 0x49, 0x51, 0xaf, 0x43, 0x5c, 0xa5, 0x68, 0x88, 0x1d, 0x41, 0x6b, 0x65, 0xf1,
	0xcc, 0x90, 0x8e, 0xe5, 0xdc, 0x73, 0xba, 0x4e, 0xaf, 0x11, 0x36, 0x33, 0x2e, 0xca, 0x28, 0xbf,
	0x07, 0xad, 0x6b, 0x1d, 0x13, 0x6e, 0x25, 0x1e, 0xd4, 0x1f, 0x8d, 0x92, 0x11, 0xe9, 0xbc, 0x7a,
	0x0b, 0xfd, 0x37, 0x07, 0x3a, 0x23, 0x15, 0xcb, 0xe8, 0xfc, 0x2a, 0x42, 0xfd, 0x1c, 0x0b, 0x0c,
	0xd1, 0x24, 0x4a, 0x1a, 0xb4, 0xa2, 0x25, 0x1a, 0xc3, 0xe7, 0xb8, 0x15, 0xe5, 0x90, 0x5d, 0x40,
	0xcd, 0x10, 0xa7, 0xd4, 0x78, 0xe5, 0xae, 0xd3, 0xfb, 0x3b, 0x08, 0x82, 0x9d, 0xcc, 0xc1, 0xe7,
	0x2d, 0x83, 0x28, 0x53, 0x85, 0xb9, 0xda, 0x3a, 0x24, 0x7c, 0xfd, 0xa4, 0xf8, 0x83, 0x57, 0xd9,
	0x38, 0xe4, 0xd0, 0x3f, 0x81, 0xda, 0xa6, 0x96, 0x35, 0xa1, 0x6e, 0x52, 0x21, 0xd0, 0x18, 0xb7,
	0xc4, 0x1a, 0x50, 0x55, 0xb4, 0x40, 0xed, 0x56, 0xed, 0x13, 0xb5, 0x56, 0xda, 0x6d, 0x0c, 0x5e,
	0xcb, 0xd0, 0xb6, 0x86, 0xd3, 0x8f, 0x00, 0xec, 0x0e, 0xfe, 0x8d, 0x34, 0x72, 0xc2, 0x22, 0x79,
	0xb8, 0x97, 0xb3, 0x38, 0xa5, 0x83, 0xe3, 0x6f, 0x7e, 0xc3, 0x2f, 0xb1, 0x5b, 0x70, 0xb3, 0x9d,
	0x7c, 0xdd, 0xbd, 0xb8, 0xb6, 0x9f, 0x74, 0xbf, 0x81, 0x3f, 0x9b, 0xf0, 0x67, 0x42, 0xa8, 0x54,
	0xd2, 0xef, 0x05, 0x1f, 0x4e, 0xa0, 0x2f, 0xd4, 0x32, 0x58, 0xa7, 0x32, 0x59, 0x70, 0x49, 0x7b,
	0xc2, 0xb9, 0x4e, 0xc4, 0x2e, 0x39, 0xfc, 0xbf, 0x33, 0xdd, 0xb1, 0x3d, 0xd4, 0xb1, 0xf3, 0x52,
	0xae, 0x84, 0xd3, 0xcb, 0xfb, 0x5a, 0x76, 0xb7, 0xa7, 0xef, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa0,
	0xae, 0x4b, 0x06, 0xd1, 0x02, 0x00, 0x00,
}
