# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'
services:
  peer-base:
    image: hyperledger/fabric-peer:${ARCH}-${FABRIC_PEER_FIXTURE_TAG}
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB

      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/msp
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ENDORSER_ENABLED=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_TLS_ENABLED=false
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
