ordererConfig:
    dirPrefix: src/main/resoures/crypto-config/ordererOrganizations
    name: Orderer
    domain: orderer.yunphant.coin.com
    host: localhost
    port: 7050
    mspdir: yunphant.coin.com/msp
channelName: coinchannel
orgDirPrefix: src/main/resources/crypto-config/peerOrganizations
artifactsDir: src/main/resources/channel-artifacts
tlsEnabled: false
organizations:
    - name: Org0
      domain: org0.yunphant.coin.com
#      mspdir: crypto-config/peerOrganizations/org0.yunphant.coin.com/msp
      mspid: Org0MSP
#      adminPrivateKey: users/Admin@org0.yunphant.coin.com/msp/keystore
#      adminCert: users/Admin@org0.yunphant.coin.com/msp/signcerts/Admin@org0.yunphant.coin.com-cert.pem
      ca:
          name: ca-org0
          host: localhost
          port: 6054
      peers:
          - name: peer0
            domain: peer0.org0.yunphant.coin.com
            host: localhost
            port: 6051
    - name: Org1
      domain: org1.yunphant.coin.com
      mspid: Org1MSP
#      adminPrivateKey: users/Admin@org1.yunphant.coin.com/msp/keystore
#      adminCert: users/Admin@org1.yunphant.coin.com/msp/signcerts/Admin@org1.yunphant.coin.com-cert.pem
      ca:
          name: ca-org1
          host: localhost
          port: 7054
      peers:
          - name: peer0
            domain: peer0.org1.yunphant.coin.com
            host: localhost
            port: 7051
    - name: Org2
      domain: org2.yunphant.coin.com
      mspid: Org2MSP
#      adminPrivateKey: users/Admin@org2.yunphant.coin.com/msp/keystore
#      adminCert: users/Admin@org2.yunphant.coin.com/msp/signcerts/Admin@org2.yunphant.coin.com-cert.pem
      ca:
          name: ca-org2
          host: localhost
          port: 8054
      peers:
          - name: peer0
            domain: peer0.org2.yunphant.coin.com
            host: localhost
            port: 8051
    - name: Org3
      domain: org3.yunphant.coin.com
      mspid: Org3MSP
#      adminPrivateKey: users/Admin@org3.yunphant.coin.com/msp/keystore
#      adminCert: users/Admin@org3.yunphant.coin.com/msp/signcerts/Admin@org3.yunphant.coin.com-cert.pem
      ca:
          name: ca-org3
          host: localhost
          port: 9054
      peers:
          - name: peer0
            domain: peer0.org3.yunphant.coin.com
            host: localhost
            port: 9051

#- &Org0:
#    name: Org0
#    domain: org0.yunphant.coin.com
##          mspdir: crypto-config/peerOrganizations/org0.yunphant.coin.com/msp
#    mspid: Org0MSP
##          org0.yunphant.coin.com/users/Admin@org0.yunphant.coin.com/msp/keystore
##          adminPrivateKey: users/Admin@org0.yunphant.coin.com/msp/keystore
##          adminCert: users/Admin@org0.yunphant.coin.com/msp/signcerts/Admin@org0.yunphant.coin.com-cert.pem
#    ca:
#        name: ca-org0
#        host: localhost
#        port: 6054
#    peers:
#        - peer0:
#              name: peer0
#              domain: peer0.org0.yunphant.coin.com
#              host: localhost
#              port: 6051
#- &Org1:
#      name: Org1
#      domain: org1.yunphant.coin.com
#      mspid: Org0MSP
##          adminPrivateKey: users/Admin@org1.yunphant.coin.com/msp/keystore
##          adminCert: users/Admin@org1.yunphant.coin.com/msp/signcerts/Admin@org1.yunphant.coin.com-cert.pem
#      ca:
#          name: ca-org1
#          host: localhost
#          port: 7054
#      peers:
#          - peer0:
#                name: peer0
#                domain: peer0.org1.yunphant.coin.com
#                host: localhost
#                port: 7051
#- &Org2:
#      name: Org2
#      domain: org2.yunphant.coin.com
##          mspdir: src/main/resources/crypto-config/peerOrganizations/org2.yunphant.coin.com/msp
#      mspid: Org2MSP
##          adminPrivateKey: src/main/resources/crypto-config/peerOrganizations/org2.yunphant.coin.com/users/Admin@org2.yunphant.coin.com/msp/keystore
##          adminCert: src/main/resources/crypto-config/peerOrganizations/org2.yunphant.coin.com/users/Admin@org2.yunphant.coin.com/msp/signcerts/Admin@org2.yunphant.coin.com-cert.pem
#      ca:
#          name: ca-org2
#          host: localhost
#          port: 8054
#      peers:
#          - peer0:
#                name: peer0
#                domain: peer0.org2.yunphant.coin.com
#                host: localhost
#                port: 8051
#- &Org3:
#      name: Org3
#      domain: org3.yunphant.coin.com
##          mspdir: src/main/resources/crypto-config/peerOrganizations/org3.yunphant.coin.com/msp
#      mspid: Org3MSP
##          adminPrivateKey: src/main/resources/crypto-config/peerOrganizations/org3.yunphant.coin.com/users/Admin@org3.yunphant.coin.com/msp/keystore
##          adminCert: src/main/resources/crypto-config/peerOrganizations/org3.yunphant.coin.com/users/Admin@org3.yunphant.coin.com/msp/signcerts/Admin@org3.yunphant.coin.com-cert.pem
#      ca:
#          name: ca-org3
#          host: localhost
#          port: 9054
#      peers:
#          - peer0:
#                name: peer0
#                domain: peer0.org3.yunphant.coin.com
#                host: localhost
#                port: 9051