# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'
networks:
  sdk_net:
    driver: bridge

services:
  couchdb0:
    networks:
      - sdk_net
    container_name: couchdb0
    image: hyperledger/fabric-couchdb:${ARCH}-${FABRIC_PEER_FIXTURE_TAG}
    ports:
      - "5984:5984"
  couchdb1:
    networks:
      - sdk_net
    container_name: couchdb1
    image: hyperledger/fabric-couchdb:${ARCH}-${FABRIC_PEER_FIXTURE_TAG}
    ports:
      - "6984:5984"
  couchdb2:
    networks:
      - sdk_net
    container_name: couchdb2
    image: hyperledger/fabric-couchdb:${ARCH}-${FABRIC_PEER_FIXTURE_TAG}
    ports:
      - "7984:5984"
  couchdb3:
    networks:
      - sdk_net
    container_name: couchdb3
    image: hyperledger/fabric-couchdb:${ARCH}-${FABRIC_PEER_FIXTURE_TAG}
    ports:
      - "8984:5984"

  ca0:
    image: hyperledger/fabric-ca:${ARCH}-${FABRIC_PEER_FIXTURE_TAG}
    networks:
      - sdk_net
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org0
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.yunphant.coin.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/b20fdc75ba4b9906de0ead441a6ad409f145b78a6971d367fd722214475878ff_sk
    ports:
      - "6054:7054"
#    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org0.yunphant.coin.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/fc603811550160584f631e3ff9dc201c96bff201ece04bbadf73f7df29eb357b_sk -b admin:adminpw -d'
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org0.yunphant.coin.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg0
  ca1:
    image: hyperledger/fabric-ca:${ARCH}-${FABRIC_PEER_FIXTURE_TAG}
    networks:
      - sdk_net
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.yunphant.coin.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/b20fdc75ba4b9906de0ead441a6ad409f145b78a6971d367fd722214475878ff_sk
    ports:
      - "7054:7054"
#    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.yunphant.coin.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/0a976d5df7418fbfe3cc69102527892d852691988235190f01fb3521b427738d_sk -b admin:adminpw -d'
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.yunphant.coin.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1
  ca2:
    image: hyperledger/fabric-ca:${ARCH}-${FABRIC_PEER_FIXTURE_TAG}
    networks:
      - sdk_net
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.yunphant.coin.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/b20fdc75ba4b9906de0ead441a6ad409f145b78a6971d367fd722214475878ff_sk
    ports:
      - "8054:7054"
#    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.yunphant.coin.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/1ee34ec81b056068ccb0352670541ea68c508e7c5c50aec96029bdd08d547791_sk -b admin:adminpw -d'
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.yunphant.coin.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg2
  ca3:
    image: hyperledger/fabric-ca:${ARCH}-${FABRIC_PEER_FIXTURE_TAG}
    networks:
      - sdk_net
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org3
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.yunphant.coin.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/b20fdc75ba4b9906de0ead441a6ad409f145b78a6971d367fd722214475878ff_sk
    ports:
      - "9054:7054"
#    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org3.yunphant.coin.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/edb58005f069e39dbb4fa2d4af7867709554433a5328a225d49e1967e3f4f909_sk -b admin:adminpw -d'
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org3.yunphant.coin.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg3

  orderer.yunphant.coin.com:
    container_name: orderer.yunphant.coin.com
    image: hyperledger/fabric-orderer:${ARCH}-${FABRIC_PEER_FIXTURE_TAG}
    networks:
      - sdk_net
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - GRPC_TRACE=all=true,
      - GRPC_VERBOSITY=debug
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/yunphant.coin.com/orderers/orderer.yunphant.coin.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/yunphant.coin.com/orderers/orderer.yunphant.coin.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050
  peer0.org0.yunphant.coin.com:
    container_name: peer0.org0.yunphant.coin.com
    networks:
      - sdk_net
    environment:
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_PEER_ID=peer0.org0.yunphant.coin.com
      - CORE_PEER_ADDRESS=peer0.org0.yunphant.coin.com:7051
#      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.org0.yunphant.coin.com:7502
#      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7502
      - CORE_PEER_EVENTS_ADDRESS=peer0.org0.yunphant.coin.com:7053
#      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:7053
#      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org0.yunphant.coin.com:7051
#      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=0.0.0.0:7051
      - CORE_PEER_LOCALMSPID=Org0MSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=resources_sdk_net
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org0.yunphant.coin.com/peers/peer0.org0.yunphant.coin.com/msp:/etc/hyperledger/msp/peer/msp
        - ./crypto-config/peerOrganizations/org0.yunphant.coin.com/peers/peer0.org0.yunphant.coin.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 6051:7051
      - 6052:7052
      - 6053:7053
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    depends_on:
      - orderer.yunphant.coin.com
      - builder
  peer0.org1.yunphant.coin.com:
    container_name: peer0.org1.yunphant.coin.com
    networks:
      - sdk_net
    environment:
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_PEER_ID=peer0.org1.yunphant.coin.com
      - CORE_PEER_ADDRESS=peer0.org1.yunphant.coin.com:7051
#      - CORE_PEER_ADDRESS=0.0.0.0:8051
#      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.org1.yunphant.coin.com:7052
#      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
#      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:8053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.yunphant.coin.com:7051
#      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=0.0.0.0:8051
#      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org0.yunphant.coin.com:7051
#      - CORE_PEER_GOSSIP_BOOTSTRAP=0.0.0.0:7051
      - CORE_PEER_LOCALMSPID=Org1MSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=resources_sdk_net
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org1.yunphant.coin.com/peers/peer0.org1.yunphant.coin.com/msp:/etc/hyperledger/msp/peer/msp
        - ./crypto-config/peerOrganizations/org1.yunphant.coin.com/peers/peer0.org1.yunphant.coin.com/tls:/etc/hyperledger/fabric/tls
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    depends_on:
        - orderer.yunphant.coin.com
        - builder
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053
  peer0.org2.yunphant.coin.com:
    container_name: peer0.org2.yunphant.coin.com
    networks:
      - sdk_net
    environment:
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_PEER_ID=peer0.org2.yunphant.coin.com
      - CORE_PEER_ADDRESS=peer0.org2.yunphant.coin.com:7051
#      - CORE_PEER_ADDRESS=0.0.0.0:8051
#      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.org2.yunphant.coin.com:7052
#      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
#      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:8053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.yunphant.coin.com:7051
#      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=0.0.0.0:8051
#      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org0.yunphant.coin.com:7051
#      - CORE_PEER_GOSSIP_BOOTSTRAP=0.0.0.0:7051
      - CORE_PEER_LOCALMSPID=Org2MSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=resources_sdk_net
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org2.yunphant.coin.com/peers/peer0.org2.yunphant.coin.com/msp:/etc/hyperledger/msp/peer/msp
        - ./crypto-config/peerOrganizations/org2.yunphant.coin.com/peers/peer0.org2.yunphant.coin.com/tls:/etc/hyperledger/fabric/tls
    depends_on:
        - orderer.yunphant.coin.com
        - builder
    ports:
      - 8051:7051
      - 8052:7052
      - 8053:7053
  peer0.org3.yunphant.coin.com:
    container_name: peer0.org3.yunphant.coin.com
    networks:
      - sdk_net
    environment:
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
      - CORE_PEER_ID=peer0.org3.yunphant.coin.com
      - CORE_PEER_ADDRESS=peer0.org3.yunphant.coin.com:7051
#      - CORE_PEER_ADDRESS=0.0.0.0:8051
#      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.org3.yunphant.coin.com:7052
#      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
#      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:8053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.yunphant.coin.com:7051
#      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=0.0.0.0:8051
#      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org0.yunphant.coin.com:7051
#      - CORE_PEER_GOSSIP_BOOTSTRAP=0.0.0.0:7051
      - CORE_PEER_LOCALMSPID=Org3MSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=resources_sdk_net
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org3.yunphant.coin.com/peers/peer0.org3.yunphant.coin.com/msp:/etc/hyperledger/msp/peer/msp
        - ./crypto-config/peerOrganizations/org3.yunphant.coin.com/peers/peer0.org3.yunphant.coin.com/tls:/etc/hyperledger/fabric/tls
    depends_on:
        - orderer.yunphant.coin.com
        - builder
    ports:
      - 9051:7051
      - 9052:7052
      - 9053:7053
  builder:
    image: hyperledger/fabric-ccenv:${ARCH}-${FABRIC_PEER_FIXTURE_TAG}
    command: tail -F anything
#  cli:
#    container_name: cli
#    image: hyperledger/fabric-tools
#    tty: true
#    environment:
#      - GOPATH=/opt/gopath
#      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
#      - CORE_LOGGING_LEVEL=DEBUG
#      - CORE_PEER_ID=cli
#      - CORE_PEER_ADDRESS=peer0.org0.yunphant.coin.com:7051
#      - CORE_PEER_LOCALMSPID=Org1MSP
#      - CORE_PEER_TLS_ENABLED=false
#      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.yunphant.coin.com/peers/peer0.org0.yunphant.coin.com/tls/server.crt
#      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.yunphant.coin.com/peers/peer0.org0.yunphant.coin.com/tls/server.key
#      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.yunphant.coin.com/peers/peer0.org0.yunphant.coin.com/tls/ca.crt
#      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.yunphant.coin.com/users/Admin@org1.yunphant.coin.com/msp
#    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
#    #  command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME}; sleep $TIMEOUT'
#    volumes:
#        - /var/run/:/host/var/run/
#        - ../chaincode/go/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
#        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
#        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
#        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
#    depends_on:
#      - ca0
#      - orderer.yunphant.coin.com
#      - peer0.org0.yunphant.coin.com
#      - peer1.org1.yunphant.coin.com

